<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<IsPackable>false</IsPackable>
		<IsTestProject>true</IsTestProject>
		<LangVersion>latest</LangVersion>
		<Nullable>enable</Nullable>
		<TargetFramework>net8.0-windows</TargetFramework>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Coverlet.Collector" Version="10.0.1">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="DigitalZenWorks.Common.Utilities" Version="1.5.78" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.8.1" />
		<PackageReference Include="NUnit" Version="4.6.1" />
		<PackageReference Include="NUnit.Analyzers" Version="4.14.0">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="NUnit3TestAdapter" Version="6.2.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="../MsAccessJetAceTool/MsAccessJetAceTool.csproj" />
	</ItemGroup>

	<ItemGroup>
		<AdditionalFiles Include="..\stylecop.json" />
		<EmbeddedResource Include="test.accdb">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</EmbeddedResource>
		<EmbeddedResource Include="test.sql">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</EmbeddedResource>
	</ItemGroup>

</Project>
