<table width="100%" cellspacing="0" cellpadding="0">
   <tr>
      <td align="right" bgcolor="#9c0001" cellspacing="0" cellpadding="0" width="100%" height="20">
         <font size="2" color="#ffffff">Welcome:
         <asp:Label id="eMail" runat="server">username</asp:Label>&nbsp; </font>
      </td>
   </tr>
   <tr>
      <td align="right" width="100%" bgcolor="#d3c9c7" height="70">
         <font size="6" color="#ffffff">
         <asp:Label id="siteName" Runat="server">Micro-site Banner</asp:Label>&nbsp; </font>
      </td>
   </tr>
</table>

